### ISSUE TITLE
The circular image has sharp edges

### ISSUE THREAD

**Issue by dhiman252** [bebensiganteng/Simple-PHP-Circular-Image-Crop#2]
I have cropped a image using this script and i have found that the corners of the image are very sharp, is there any way such that the image can have smooth corners ?
I have also attached the sample image which is cropped using this php script
![hassan_143082453086780331](https://cloud.githubusercontent.com/assets/8954468/7471898/10800b40-f34a-11e4-863a-4fef9b36e834.png)

**Comment by bebensiganteng** [comment]
@dhiman252 , you need to embed the image half of its size. 

``` html
 <!-- 
        Just divide the actual size to your liking
        width = 222px/3 = 74
        height = 220px/3 = 73.3333
    -->
    <img src="image.php?path=sample.jpg" width="74" height="73">
```

Have a look at my example html
